In [1]:
import pandas as pd

pd.set_option('display.float_format', '{:,.2f}'.format)

In [75]:
df = pd.read_excel('2025 Payments.xlsx')

In [67]:
dec = pd.read_excel('Unknown.xlsx')

In [68]:
dec.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year
0,1001327670-4,228009001,BOARD FOR TECHNOLOGY BUSINESS INCUBATOR CENTRE...,FAITHKHALI CONSTRUCTION COMPANY LIMITED,"14,018,424.92",BEING PAYMENT IFO THE ABOVE NAMED COMPANY FOR ...,2025-12-08,12,Contractor,2025
1,1001327275-4,228009001,BOARD FOR TECHNOLOGY BUSINESS INCUBATOR CENTRE...,GEOBASS UNIVERSAL CONCEPTS LTD,"6,898,478.56",ERGP10204709 BEING PAYMENT FOR THE AWARD OF CO...,2025-12-08,12,Contractor,2025
2,1001330160-4,161022001,BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) H...,PACIFIC BITUMEN AND ROADS LTD,"50,705,856.00",BEING paymenREHABILITATION OF ROAD AND CONSTRU...,2025-12-08,12,Contractor,2025
3,1001329973-3,161022001,BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) H...,PANCIO LIMITED,"25,832,948.84",BEING 100% PAYMENT FOR CONSTRUCTION OF HAND PU...,2025-12-08,12,Contractor,2025
4,1001330193-1,161022001,BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) H...,SOKOMEH INTEGRATED SERVICES LTD,"26,320,000.00",BEING 60% payment FOR THE RENOVATION OF INTERN...,2025-12-08,12,Contractor,2025

In [62]:
dec['Date'] = pd.to_datetime(dec.Date)

In [63]:
dec['Month'] = dec['Date'].dt.month

In [11]:
mega = pd.read_excel('2020 to 2025 Gov Expenditure Dataset.xlsx')

In [34]:
mega.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,COFOG Code,MDA,Organization
0,1000659435-65,232002001,DEPARTMENT OF PETROLEUM RESOURCES,SULEIMAN ILIYASU LAWAL TANIMU,"5,282,111.00",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES
1,1000659420-23,232002001,DEPARTMENT OF PETROLEUM RESOURCES,EKEKHIDE JENNIFER OSHIONE,"8,750,704.78",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES
2,1000659435-69,232002001,DEPARTMENT OF PETROLEUM RESOURCES,NJOKU KELECHI CHIAKA,"5,282,929.97",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES
3,1000659420-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,BIGHORO SYLVESTER EDIRIN,"7,569,966.14",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES
4,1000659435-1,232002001,DEPARTMENT OF PETROLEUM RESOURCES,UMARU AHMADU,"5,841,144.67",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES

In [54]:
mda_list = df[df.Type=='MDA']['Beneficiary Name'].unique()
con_list = df[df.Type=='Contractor']['Beneficiary Name'].unique()
ind_list = df[df.Type=='Individual']['Beneficiary Name'].unique()

In [64]:
dec['Type'] = 'Unknown'

dec.loc[dec['Beneficiary Name'].isin(mda_list), 'Type'] = 'MDA'
dec.loc[dec['Beneficiary Name'].isin(con_list), 'Type'] = 'Contractor'
dec.loc[dec['Beneficiary Name'].isin(ind_list), 'Type'] = 'Individual'

In [65]:
dec['Type'].value_counts()

Type
MDA           8509
Contractor    6163
Unknown       3711
Individual     337
Name: count, dtype: int64

In [66]:
dec.to_excel('Unknown.xlsx', index=False)

In [9]:
df.to_excel("2025 Payments.xlsx", index=False)

In [39]:
orgs = pd.read_excel("Organizations.xlsx")

In [33]:
org_list = orgs[['Organization Name','COFOG Code', "MDA", "Location", "Region", "Organization"]]

In [5]:
orgs.head()

,Organization Name,COFOG Code,MDA,Location,Region,Organization,Acronym,Website
0,ABUBAKAR TAFAWA BALEWA UNIVERSITY TEACHING HOS...,7,Federal Ministry of Health & Social Welfare,Bauchi,North East,ABUBAKAR TAFAWA BALEWA UNIVERSITY TEACHING HOS...,NaN,NaN
1,"ABUBAKAR TAFAWA BALEWA UNIVERSITY, BAUCHI",9,Federal Ministry of Education,Bauchi,North East,ABUBAKAR TAFAWA BALEWA UNIVERSITY,NaN,NaN
2,ACCIDENT AND INVESTIGATION BUREAU,3,Federal Ministry of Aviation & Aerospace Devel...,Lagos,South West,ACCIDENT AND INVESTIGATION BUREAU,NaN,NaN
3,ADMINISTRATIVE STAFF COLLEGE OF NIGERIA,9,Office of the Head of the Civil Service of the...,Lagos,South West,ADMINISTRATIVE STAFF COLLEGE OF NIGERIA,NaN,NaN
4,"ADMIRALTY UNIVERSITY OF NIGERIA, IBUSA, DELTA ...",9,Federal Ministry of Defence,Delta,South South,ADMIRALTY UNIVERSITY OF NIGERIA,NaN,NaN

In [45]:
df.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,COFOG Code,MDA,Organization,Location,Region
56923,1000659421-19,232002001,DEPARTMENT OF PETROLEUM RESOURCES,OKON ANIETIE EDET,"9,693,789.66",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES,FCT,North Central
56838,1000659401-21,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MUREY BENJAMIN,"5,925,356.70",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES,FCT,North Central
56839,1000659423-19,232002001,DEPARTMENT OF PETROLEUM RESOURCES,OSIFO PAUL OMOREGIE,"8,206,663.43",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES,FCT,North Central
56840,1000659401-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,ABUBAKAR MOHAMMED NAKO,"7,062,233.27",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES,FCT,North Central
56841,1000659440-20,232002001,DEPARTMENT OF PETROLEUM RESOURCES,RABIU USMAN,"5,796,429.59",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES,FCT,North Central

In [76]:
df = df.merge(orgs[['Organization Name','COFOG Code', "MDA", "Location", "Region", "Organization"]], how='left', on='Organization Name')

In [77]:
df = df.drop("Account", axis=1)

In [78]:
df_list = [df, dec, mega]

In [79]:
df = pd.concat(df_list, ignore_index=True)

In [80]:
df.sort_values(by="Date", inplace=True)

In [82]:
df[df['Year'] == 2025].head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,COFOG Code,MDA,Location,Region,Organization
865,1001262613-61,535015001,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY,Access Pensions Limited,"7,907,841.34",JAN 2025 NATIONAL OIL SPILL D -Access Pension...,2025-02-03,2,Contractor,2025,5.00,Federal Ministry of Environment,FCT,North Central,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY
864,1001262613-62,535015001,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY,Norrenberger Pension Limited,"5,738,298.28",JAN 2025 NATIONAL OIL SPILL D -Norrenberger P...,2025-02-03,2,Contractor,2025,5.00,Federal Ministry of Environment,FCT,North Central,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY
863,1001262613-73,535015001,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY,NHF,"15,235,579.15",JAN 2025 NATIONAL OIL SPILL D -NHF,2025-02-03,2,MDA,2025,5.00,Federal Ministry of Environment,FCT,North Central,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY
862,1001262613-74,535015001,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY,NHIS,"6,073,690.23",JAN 2025 NATIONAL OIL SPILL D -NHIS,2025-02-03,2,MDA,2025,5.00,Federal Ministry of Environment,FCT,North Central,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY
861,1001262613-6,535015001,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY,LAGOS TAX,"5,091,587.42",JAN 2025 NATIONAL OIL SPILL D -LAGOS TAX,2025-02-03,2,MDA,2025,5.00,Federal Ministry of Environment,FCT,North Central,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY

In [83]:
df.to_excel("20-25 Payments.xlsx", index=False)

In [30]:
df[df['MDA'].isna() == True]['Organization Name'].unique()

array(['NATIONAL SPORTS COMMISSION HQTRS',
       'OFFICE OF THE SENIOR SPECIAL ASSISTANT TO THE PRESIDENT MDG (OSSAP-MDGs)',
       'NATIONAL AGRICULTURAL DEVELOPMENT FUND (NADFund)',
       'DEFENCE HEADQUARTERS', 'DEFENCE SPACE ADMINISTRATION',
       'ALVAN IKOKU UNIVERSITY OF EDUCATION, OWERRI, IMO STATE',
       'NATIONAL ANIMAL PRODUCTION RESEARCH INSTITUTE-ZARIA, KADUNA STATE',
       'DAVID UMAHI FEDERAL UNIVERSITY OF HEALTH SCIENCES, UBURU, EBONYI STATE',
       'FEDERAL MINISTRY OF WATER RESOURCES AND SANITATION - HQTRS',
       'FEDERAL UNIVERSITY GASHUA', 'AIR POWER CENTRE OF EXCELLENCE',
       'DEFENCE SPACE SCHOOL, OROGUN, DELTA STATE',
       'FEDERAL MEDICAL CENTRE IKOLE-EKITI, EKITI STATE',
       'FEDERAL UNIVERSITY OF GUSAU', 'FEDERAL UNIVERSITY BIRNIN KEBBI',
       'ADEYEMI FEDERAL UNIVERSITY OF EDUCATION, ONDO',
       'NATIONAL VETERINARY RESEARCH INSTITUTE-VOM, PLATEAU STATE',
       'NIGERIAN INSTITUTE FOR OCEANOGRAPHY AND MARINE RESEARCH',
       'NATIONAL INSTITUTE FOR FRESH WATER FISHERIES RESEARCH-NEW BUSSA',
       'NATIONAL CYBERCRIME COORDINATION CENTRE (NCCC)',
       'NIGERIAN INSTITUTE OF ANIMAL SCIENCE, ABUJA',
       'FEDERAL COLLEGE OF VETERINARY AND MEDICAL LABORATORY TECHNOLOGY, VOM, PLATEAU STATE',
       'FEDERAL COLLEGE OF ANIMAL HEALTH AND PRODUCTION TECHNOLOGY-IBADAN, OYO STATE',
       'NATIONAL UNIVERSITY OF SCIENCE AND TECHNOLOGY, ABUJA, FCT.',
       'FEDERAL UNIVERSITY OF HEALTH SCIENCES TEACHING HOSPITAL, ILA -ORANGUN, OSUN STATE',
       'FEDERAL MEDICAL CENTRE, EPE',
       'FEDERAL MEDICAL CENTRE MISAU, BAUCHI',
       'FEDERAL COLLEGE OF ANIMAL HEALTH AND PRODUCTION TECHNOLOGY, VOM, PLATEAU STATE',
       'FEDERAL MINISTRY OF LIVESTOCK DEVELOPMENT',
       'NATIONAL COMMISSION FOR NOMADIC EDUCATION',
       'FOREIGN MISSION   :   ALGIERS',
       'FEDERAL UNIVERSITY TEACHING HOSPITAL, LAFIA, NASARAWA STATE',
       'NATIONAL INTELLIGENCE AGENCY PENSION BOARD',
       'ADVERTISING REGULATORY COUNCIL OF NIGERIA (ARCON)'], dtype=object)

In [36]:
mega = mega.merge(orgs[['Organization Name', 'Location', 'Region']], how='left', on="Organization Name")

In [37]:
mega.to_excel("2020 to 2025 Gov Expenditure Dataset.xlsx", index=False)

In [4]:
untagged_df = pd.read_excel("Contractors_FINAL.xlsx")
tagged_df = pd.read_excel("Final.xlsx")

remaining_df = untagged_df[
    ~untagged_df["Beneficiary Name"].isin(tagged_df["Beneficiary Name"])
]

remaining_df.to_excel("Contractors_UNTAGGED_ONLY.xlsx", index=False)